### ISSUE TITLE
Specify collection name.

### ISSUE THREAD

**Issue by jgornick** [fortunejs/fortune-mongodb#12]
I'm not understanding why the type must match the collection name. If I create a type called "card", I would expect the collection to be called "cards". Is there a way to transform or specify the collection for the type "card"?

**Comment by 0x8890** [comment]
It's just for simplicity's sake. There's no reason why there can't be an arbitrary mapping of type to collection name, it just hasn't been implemented. PR would be welcome, otherwise it wouldn't be a difficult thing for me to do.

**Comment by 0x8890** [comment]
Done in commit bc41373d70a576dc83459f4cd6bd0a91e0779efc, published as `1.0.2`.
