### ISSUE TITLE
Weird ids

### ISSUE THREAD

**Issue by jlcarvalho** [fortunejs/fortune-mongodb#14]
I got this generated id: `/f9XL5u+VDM426bToRc1`.
So, when i tried to access `GET /people//f9XL5u+VDM426bToRc1` i got:

```json
{
    "errors": [
        {
            "title": "NotFoundError",
            "detail": "The field \"f9XL5u+VDM426bToRc1\" is not a link on the type \"people\"."
        }
    ]
}
```

After some investigation i found this function:
```js
export function generateId () {
  return crypto.randomBytes(15).toString('base64')
}
```

Running in node shell:
![captura de tela 2015-09-10 as 02 30 30](https://cloud.githubusercontent.com/assets/1238663/9780822/f3e532f2-5763-11e5-8b09-689314edc824.png)

Sometimes  `base64` returns the `/` char.
Use `hex` instead of `base64` would be a quick fix.

```js
crypto.randomBytes(15).toString('hex')
```

**Comment by 0x8890** [comment]
Actually this is not a bug and is intended behavior to get people to use proper URI encoding :)

See my response in https://github.com/fortunejs/fortune/issues/130.
