### ISSUE TITLE
No errors but no action

### ISSUE THREAD

**Issue by ksnyde** [fortunejs/fortune-mongodb#16]
I've got Fortune working with JSON-API and that worked very seamlessly but when trying to add the mongodb plugin it seems to never engage. By "engage" I mean I am watching the mongo logs and no connection attempt seems to be made (either initially or when I add data through POST calls to the API). Furthermore, while Fortune is clearly collecting state it never gets persisted to Mongo. 

Here's the test script I'm using:

    const fortune = require('fortune');
    const MongodbAdapter = require('fortune-mongodb');
    const Fortune = fortune({
      adapter: {
        type: MongodbAdapter,
        options: {
          url: 'mongodb://localhost:27017/test',
          typeMap: {
            user: 'users',
            group: 'groups'
          }
        }
      }
    });
    const http = require('http');
    const jsonApi = require('fortune-json-api');
    const store = fortune({
      serializers: [{
        type: jsonApi,
        options: {},
      }]
    });

    const listener = fortune.net.http(store);
    const server = http.createServer(listener);
    const port = 1337;

    store.defineType('user', {
      username: {
        type: String,
      },
      key: {
        type: Buffer,
      },
      salt: {
        type: Buffer,
      },
      group: {
        link: 'group',
        inverse: 'users',
        isArray: true,
      },
    });

    store.defineType('group', {
      name: {
        type: String
      },
      users: {
        link: 'user',
        inverse: 'group',
        isArray: true
      },
    });

    store.connect().then(() => {
      server.listen(port)
      console.log(`Server is listening on port ${port}...`)
    })

I'm using Mongo for the first time today so possibly I'm missing something obvious but would LOVE some help in getting this working.

**Comment by ksnyde** [comment]
nevermind, figured it out.

**Comment by 0x8890** [comment]
Just curious, what was the problem?

**Comment by ksnyde** [comment]
i defined two fortune objects -- `store` and `Fortune` -- by combining the configuration into a single object everything worked. Silly newbie issue. :)

Great library, still early exploration but really like it so far. Do you know if it's being used anywhere in scale?

**Comment by 0x8890** [comment]
I know of a few companies which are using it, though only because they have bothered to contact me at all. I'm not really interested in gathering a list of users, though.
