### ISSUE TITLE
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect

### ISSUE THREAD

**Issue by Truemedia** [fortunejs/fortune-mongodb#24]
Hi,
I know this is just warning but as it states this will eventually mean this adapter will be incompatible with newer version of mongodb.

I know the way to address this is by emitting the db name from the url and passing as a parameter to the Mongo instance decleration.

I have done this before but would be trickier to implement here as I don't know this codebase. I'm willing to take a look and commit though if a PR would be accepted?

**Comment by gr0uch** [comment]
Done: https://github.com/fortunejs/fortune-mongodb/commit/e1e5e4d830e37fdee92388ab194ba35a71dae27f
