### ISSUE TITLE
DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

### ISSUE THREAD

**Issue by Truemedia** [fortunejs/fortune-mongodb#25]
Again just another potential issue with future versions that can be fixed with just a code change (just renaming a key in this instance).

**Comment by gr0uch** [comment]
Done: https://github.com/fortunejs/fortune-mongodb/commit/e1e5e4d830e37fdee92388ab194ba35a71dae27f
